In [1]:
import numpy as np

In [40]:
ain=np.array([np.arange(9).reshape(3,3) for i in range(2)])
ain = ain.transpose(1,2,0)
print ain.shape
print ain[:,:,:]

(3, 3, 2)
[[[0 0]
  [1 1]
  [2 2]]

 [[3 3]
  [4 4]
  [5 5]]

 [[6 6]
  [7 7]
  [8 8]]]


In [44]:
dy=1
dx=1
miss = -9999
def shift_array(ain=None, dy=None,dx=None,miss=-9999):
    ny,nx,nz = ain.shape
    aout = np.ones([ny,nx,nz]).astype(ain.dtype)*miss
    if   dy<=0: iy0=0; ey0=ny-abs(dy); iy1=abs(dy); ey1=ny
    elif dy> 0: iy0=abs(dy); ey0=ny; iy1=0; ey1=ny-abs(dy)
    if   dx<=0: ix0=0; ex0=nx-abs(dx); ix1=abs(dx); ex1=nx
    elif dx> 0: ix0=abs(dx); ex0=nx; ix1=0; ex1=nx-abs(dx)
    
    aout[iy0:ey0,ix0:ex0] = ain[iy1:ey1,ix1:ex1]
    return aout
aout = shift_array(ain, dy=dy,dx=dx)
print ain[:,:,0]
print ''
print aout[:,:,0]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[-9999 -9999 -9999]
 [-9999     0     1]
 [-9999     3     4]]


[[[-9999 -9999 -9999]
  [-9999 -9999 -9999]
  [-9999 -9999 -9999]]

 [[-9999 -9999 -9999]
  [-9999 -9999 -9999]
  [-9999 -9999 -9999]]]
